name: dinov2-extras
channels:
  - conda-forge
  - defaults
  - pytorch
  - nvidia
  - xformers
dependencies:
  - python=3.10
  - omegaconf
  - fvcore
  - iopath
  - xformers::xformers
  - pip
  - pip:
    - torch==2.0.0
    - torchvision
    - torchmetrics
    - git+https://github.com/facebookincubator/submitit
    - --extra-index-url https://pypi.nvidia.com
    - cuml-cu11

